# this setting is relevant for the theme demo on the Hugo Themes website
ignoreFiles = [
  "content/posts/\\.*",
  "content/portfolio/\\.*",
  "content/product/\\.*",
  "content/en/\\.*",
  "content/fr/\\.*",
  "content/es/\\.*",
  "content/de/\\.*",
  "content/zh-tw/\\.*",
  "content/zh-cn/\\.*"
]

baseURL = "http://example.org/"
languageCode = "en"
title = "hugo-mondrian-theme"
theme = "mondrian"

[taxonomies]
  tag = "tags"

[params]
  showHeader = true
  showTags = true
  debug = false
  [params.colors]
    post = "orangered"
    posts = "gold"
    page = "blue"
    sketch = "limegreen"

[menu]
  [[menu.main]]
    name = "posts"
    url = "/post"
    weight = 1
  [[menu.main]]
    name = "sketches"
    url = "/sketch"
    weight = 2

